FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y g++ && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN g++ main.cpp rsa.cpp -Iinclude -o rsa_server

CMD ["./rsa_server"]